### ISSUE TITLE
Problem with sed command on MacOS

### ISSUE THREAD

**Issue by nilgundag** [huseyinbabal/docker_workshop#1]
I had a problem running following command on my Mac:

`sed -i "s/$OLD/$NEW/g" *`

Instead using following works fine:

`sed -i "" -e "s/$OLD/$NEW/g" *`

Looks like `sed` command works differently on Mac and Linux operating systems. And there is currently no way to make it work on both platforms (without backups):
http://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux

I thought maybe we can create different run.sh files for mac users or at least put a warning in the README file for them.

**Comment by huseyinbabal** [comment]
Thanks:) I have stated in the README file.
