### ISSUE TITLE
Accessing consul server 

### ISSUE THREAD

**Issue by nilgundag** [huseyinbabal/docker_workshop#2]
When you are accessing docker behind a VM using boot2docker or kitematic, you can not access to consul server using example command in the README:

`curl http://172.17.0.15:8500/v1/catalog/services?pretty=1`

You have to access using the ip assigned to the VM. It took me some time to discover that. So I thought we can add a warning about it in the README file for newcomers like me.

**Comment by huseyinbabal** [comment]
You are right, and in this workshop we have used linux for docker operations. Thats why we have mised to point that out. I have included the required statement i the README file. Thanks again
