### ISSUE TITLE
Skipping docker build step for rabbitmq and mongodb

### ISSUE THREAD

**Issue by nilgundag** [huseyinbabal/docker_workshop#3]
I discovered that in some of the `run.sh` files ( rabbitmq and mongodb ), the step for checking if an image already exists is commented out.  As a result the images are built from scratch everytime I run `run.sh`. While for others built step is skipped. Is there a specific reason for this?

**Comment by huseyinbabal** [comment]
Actually, it was committed by mistake. Thanks for point out :). I have uncommented and commit to the project.
